# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Nov 16 08:27:26 PST 2012
#
#/ usage: jboss-as:install  --jboss-as-package-file <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --jboss-as-package-file) rerun_option_check $# ; JBOSS_AS_PACKAGE_FILE=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [ -z "$JBOSS_AS_PACKAGE_FILE" ] && { echo >&2 "missing required option: --jboss-as-package-file" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export JBOSS_AS_PACKAGE_FILE
    #
    return 0
}


# Initialize the options variables to null.
JBOSS_AS_PACKAGE_FILE=


