# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Nov 15 10:44:53 PST 2012
#
#/ usage: jboss-as:install  --install-url <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --install-url) rerun_option_check $# ; INSTALL_URL=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [ -z "$INSTALL_URL" ] && { echo >&2 "missing required option: --install-url" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export INSTALL_URL
    #
    return 0
}


# Initialize the options variables to null.
INSTALL_URL=


