#!/usr/bin/env bash
#
#/ command: jboss-as:erase: "Erase the JBoss Application Server package(s) from the system"
#
#/ usage: rerun jboss-as:erase [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jboss-as:erase. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/erase/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/erase/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Remove jboss-as package and its dependencies from the system
sudo yum --quiet -y remove jboss-as > /dev/null 2>&1

exit $?

# Done
